### ISSUE TITLE
should there be syntactic support for reading from a ternary expression?

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/tmplr-yaml-parser#2]
[`if` is now an expression](https://github.com/loreanvictor/tmplr-core/issues/5), which means we have ternary expressions like this:

```yml
prompt: What is your project URL?
default:
  if: git.remote_provider
  eval: 'https://{{ git.remote_provider }}/{{ git.remote_owner }}/{{ git.remote_name }}'
  else:
    eval: Enter some url ...
```

However, `if` takes precedence over all other commands and expressions in its node, which particularly means `read` cannot work with ternary expressions:

```yml
read: x
if: some condition
eval: some value
else:
  eval: some other value
```

👆 this code will read x if some condition holds, but won't read it otherwise (will just evaluate some other value to oblivion), since `if` takes precedence over `read`.

this can be simply fixed by introducing an expression similar to `if` but with lower priority (right below `read`):

```yml
read: x
where: some condition
eval: some value
else:
  eval: some other value
```
👆 this code will ALWAYS read x, even without an else clause it would read it into an empty string.

this is fairly straightforward since it is a copy of if rule, however it requires further contemplation of whether it is worth adding to syntax complexity for the convenience of `read` command (and only `read` command).

## Pros

- Convenient reads with ternary expressions
- ??

## Cons

- In a lot of cases, `if` and `where` will be interchangeable, i.e. two ways to do the same thing, which increases difficulty of reading recipe code.
- In cases that they are not, it might be confusing.
- Potential clash with [this proposal](https://github.com/loreanvictor/tmplr/issues/24). This is not a case of actual syntax ambiguity, since `where` would have lower priority to `copy`/`update`/`remove` (and other such commands). However it might result in increased difficulty of reading recipe code.
- ??

This should be further contemplated. For now, I will add the code and tests for the `where` rule, without adding it to the standard ruleset (should it be a parametrised `if` rule instead?)
